### ISSUE TITLE
Link from interface to GitHub issues

### ISSUE THREAD

**Issue by jameshowison** [kermitt2/kish#10]
Perhaps a link from the kish interface to the GitHub repo?  I looked for it top right, something using https://github.com/tholman/github-corners perhaps?

**Comment by kermitt2** [comment]
There's currently a discreet link to the Github repo at the foot of page application.

![Screenshot from 2023-04-13 16-13-29](https://user-images.githubusercontent.com/2340795/231786616-38a3f8c5-f9a3-4250-a4f5-3f2660347e04.png)

**Comment by jameshowison** [comment]
Right on!
